# Generated by Django 5.2.5 on 2025-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenant_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_schema',
            field=models.CharField(blank=True, db_index=True, help_text='Schema name of the tenant this user belongs to. Empty for SuperAdmins.', max_length=63),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_schema'], name='tenant_user_tenant__aecfdd_idx'),
        ),
    ]
