# Generated by Django 5.2.5 on 2025-10-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenant_users', '0002_add_tenant_schema_field'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'tenant_schema'), name='unique_username_per_tenant'),
        ),
    ]
