# Generated by Django 5.2.5 on 2025-10-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_low_stock_threshold_stock_reorder_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
